//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessTable
    {
        public int AccessID { get; set; }
        public Nullable<int> UserTypeID { get; set; }
        public Nullable<int> ViewID { get; set; }
        public Nullable<int> ModuleID { get; set; }
    
        public virtual ModuleTable ModuleTable { get; set; }
        public virtual UserTypeTable UserTypeTable { get; set; }
        public virtual ViewsTable ViewsTable { get; set; }
    }
}
