//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassCreationTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClassCreationTable()
        {
            this.ClassDivisionTables = new HashSet<ClassDivisionTable>();
        }
    
        public int ClassCreationID { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public string Class { get; set; }
    
        public virtual SchoolTable SchoolTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClassDivisionTable> ClassDivisionTables { get; set; }
    }
}
