//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeeTable
    {
        public int FeeID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> CurrentFee { get; set; }
        public Nullable<int> Arears { get; set; }
        public Nullable<int> Surcharge { get; set; }
        public Nullable<int> Fines { get; set; }
    
        public virtual StudentTable StudentTable { get; set; }
    }
}
