//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarksTable
    {
        public int MarksID { get; set; }
        public Nullable<int> AcedamicYearID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> StudentDivissionID { get; set; }
        public Nullable<int> SubjectCreationID { get; set; }
        public Nullable<int> ExamID { get; set; }
        public Nullable<int> StaffDetailID { get; set; }
        public Nullable<int> MarksObtained { get; set; }
        public Nullable<int> TotalMarks { get; set; }
        public string Status { get; set; }
    
        public virtual AcedamicYearTable AcedamicYearTable { get; set; }
        public virtual ClassDivisionTable ClassDivisionTable { get; set; }
        public virtual ExamTable ExamTable { get; set; }
        public virtual StaffTable StaffTable { get; set; }
        public virtual StudentTable StudentTable { get; set; }
        public virtual SubjectClassTable SubjectClassTable { get; set; }
    }
}
