//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParentTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ParentTable()
        {
            this.StudentTables = new HashSet<StudentTable>();
        }
    
        public int ParentID { get; set; }
        public string ParentName { get; set; }
        public Nullable<int> ParentNumber { get; set; }
        public string ParentAddress { get; set; }
        public string RelationToStudent { get; set; }
        public string ParentEmail { get; set; }
        public Nullable<int> UserTypeID { get; set; }
    
        public virtual UserTypeTable UserTypeTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentTable> StudentTables { get; set; }
    }
}
