//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalaryTable
    {
        public int SalaryID { get; set; }
        public Nullable<int> StaffID { get; set; }
        public Nullable<int> SalaryAmount { get; set; }
        public Nullable<int> Bonuses { get; set; }
    
        public virtual StaffTable StaffTable { get; set; }
    }
}
