//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StaffTable()
        {
            this.MarksTables = new HashSet<MarksTable>();
            this.SalaryTables = new HashSet<SalaryTable>();
            this.StaffClassTables = new HashSet<StaffClassTable>();
            this.StaffEduDetailsTables = new HashSet<StaffEduDetailsTable>();
        }
    
        public int StaffID { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public string StaffName { get; set; }
        public string StaffDOB { get; set; }
        public string StaffMaritalStatus { get; set; }
        public string StaffGender { get; set; }
        public string StaffCity { get; set; }
        public string StaffDistrict { get; set; }
        public string StaffProvince { get; set; }
        public string StaffPersonalNumber { get; set; }
        public Nullable<int> UserCreationID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MarksTable> MarksTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalaryTable> SalaryTables { get; set; }
        public virtual SchoolTable SchoolTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StaffClassTable> StaffClassTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StaffEduDetailsTable> StaffEduDetailsTables { get; set; }
        public virtual UserCreationTable UserCreationTable { get; set; }
    }
}
