//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffEduDetailsTable
    {
        public int SEDID { get; set; }
        public Nullable<int> StaffDetailID { get; set; }
        public string DegreeName { get; set; }
        public string Institute { get; set; }
        public Nullable<int> PassingYear { get; set; }
    
        public virtual StaffTable StaffTable { get; set; }
    }
}
