//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffClassTable
    {
        public int StaffClassID { get; set; }
        public Nullable<int> StaffDetailID { get; set; }
        public Nullable<int> StudentDivissionID { get; set; }
        public Nullable<int> SubjectID { get; set; }
    
        public virtual ClassDivisionTable ClassDivisionTable { get; set; }
        public virtual StaffTable StaffTable { get; set; }
        public virtual SubjectTable SubjectTable { get; set; }
    }
}
