//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentClassTable
    {
        public int StudentClassID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> ClassDivissionID { get; set; }
        public Nullable<int> AcedamicYearID { get; set; }
    
        public virtual ClassDivisionTable ClassDivisionTable { get; set; }
        public virtual StudentTable StudentTable { get; set; }
    }
}
