//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StudentTable()
        {
            this.FeeTables = new HashSet<FeeTable>();
            this.MarksTables = new HashSet<MarksTable>();
            this.StudentClassTables = new HashSet<StudentClassTable>();
            this.StudentPreviousAcedamicTables = new HashSet<StudentPreviousAcedamicTable>();
        }
    
        public int StudentID { get; set; }
        public string StudentName { get; set; }
        public string StudentDOB { get; set; }
        public string StudentGender { get; set; }
        public string StudentCity { get; set; }
        public string StudentRegNumber { get; set; }
        public string StudentProvince { get; set; }
        public string StudentPicture { get; set; }
        public string DateEnroll { get; set; }
        public Nullable<int> UserCreationID { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public Nullable<int> ParentID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FeeTable> FeeTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MarksTable> MarksTables { get; set; }
        public virtual ParentTable ParentTable { get; set; }
        public virtual SchoolTable SchoolTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentClassTable> StudentClassTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentPreviousAcedamicTable> StudentPreviousAcedamicTables { get; set; }
        public virtual UserCreationTable UserCreationTable { get; set; }
    }
}
