//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentRegistration
    {
        public int StudentID { get; set; }
        public string StudentName { get; set; }
        public string StudentDOB { get; set; }
        public string StudentGender { get; set; }
        public string StudentCity { get; set; }
        public string StudentRegNumber { get; set; }
        public string StudentProvince { get; set; }
        public string StudentPicture { get; set; }
        public string DateEnroll { get; set; }
        public Nullable<int> UserCreationID { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<int> USerTypeID { get; set; }
        public string ParentEmail { get; set; }
        public string RelationToStudent { get; set; }
        public string ParentAddress { get; set; }
        public Nullable<int> ContacNumber { get; set; }
        public string ParentName { get; set; }
        public Nullable<int> Percentage { get; set; }
        public string PreviousSchoolName { get; set; }
        public int SPATID { get; set; }
    }
}
